### ISSUE TITLE
Relative import path "comlink" not prefixed with / or ./ or ../

### ISSUE THREAD

**Issue by RenChaoX** [vicary/deno-workerpool#2]
window10
deno 1.37.0

Copying official demo, unable to run
![image](https://github.com/vicary/deno-workerpool/assets/8422702/626cb97b-d3a5-47d7-995b-1001941d3a71)
![image](https://github.com/vicary/deno-workerpool/assets/8422702/dc3b36aa-84c2-463f-bf0e-fa1254bd65d6)

**Comment by vicary** [comment]
A lot has changed since my last publish, I may need to redo it with `dnt` and publish to npm instead of denoland.

Will take some time to experiment this weekend.

**Comment by AnonDev2244** [comment]
Hello! Any success with that? I am trying to use your worker pool and face the same issue.

**Comment by vicary** [comment]
Looks like `deno.json` in modules are no longer respected, I replaced it with `deps.ts` in `0.2.5`.

`Workerpool` is meant to be an abstract primitive, it needs an implementation of `enqueue` and `dequeue`.

If you want to quickly test it out, copy the In-Memory queue example instead of basic usage.

Feel free to reopen if you hit anything.
